# model config
hidden_size: 50
concat_size: 128
n_proposals: 100
im_feat_size: 512 # TODO: Only use scene graph features for now
im_scene_feat_size: 512
use_scene: False
word_emb_size: 200
language_model: models/glove/glove.twitter.27B.200d.txt
checkpoint: models/grounder_multi.ckpt

# training parameters
batch_size: 64
n_epochs: 40
learning_rate: 0.001
sched_steps: [15, 25]
weight_decay: 0.0005
print_every: 100
evaluate_every: 50000

# misc
confidence: 0.5
iou_threshold: 0.5
crop_size: 224

ids:
  all: all.txt
  train: train.txt
  val: val.txt
  test: test.txt
  nobbox: nobbox.txt

dirs:
  entities:
    root: /home/siyi/flickr30k_entities
    anno: /home/siyi/flickr30k_entities/Annotations
    sent: /home/siyi/flickr30k_entities/Sentences

  images:
    root: /home/siyi/flickr30k-images
    proposals: proposals

  features: features_scene_graph  # TODO: Only use scene graph features for now
  scene_features: features_scene_graph
  annotations: annotations_multi

  tmp:
    root: tmp
    word2idx: tmp/word2idx_multi.pkl
    pretrained_embeddings: tmp/embedding_multi.npy


